import { DayPlan } from '../types'

export const MOCK_MENU: DayPlan[] = [
  {
    dayNumber: 1,
    breakfast: {
      id: 'mock_b1',
      name: 'Овсянка с бананом',
      description: 'Быстрая овсяная каша с бананом и мёдом.',
      mealType: 'breakfast',
      cookingTime: 10,
      difficulty: 'easy',
      ingredients: [
        { id: 'oats', name: 'Овсяные хлопья', amount: 80, unit: 'г', category: 'storable' },
        { id: 'milk', name: 'Молоко', amount: 200, unit: 'мл', category: 'perishable' },
        { id: 'banana', name: 'Банан', amount: 1, unit: 'шт', category: 'perishable' },
        { id: 'honey', name: 'Мёд', amount: 1, unit: 'ст.л.', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Довести молоко до кипения, добавить хлопья.' },
        { stepNumber: 2, instruction: 'Варить 5 минут, помешивая.' },
        { stepNumber: 3, instruction: 'Нарезать банан, выложить сверху, полить мёдом.' },
      ],
    },
    lunch: {
      id: 'mock_l1',
      name: 'Куриный суп с лапшой',
      description: 'Лёгкий куриный суп с овощами и лапшой.',
      mealType: 'lunch',
      cookingTime: 35,
      difficulty: 'easy',
      ingredients: [
        { id: 'chicken', name: 'Куриное филе', amount: 200, unit: 'г', category: 'perishable' },
        { id: 'noodles', name: 'Лапша', amount: 80, unit: 'г', category: 'storable' },
        { id: 'carrot', name: 'Морковь', amount: 80, unit: 'г', category: 'storable' },
        { id: 'salt', name: 'Соль', amount: 0, unit: 'по вкусу', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Сварить курицу, вытащить и нарезать.' },
        { stepNumber: 2, instruction: 'В бульон добавить морковь и лапшу.' },
        { stepNumber: 3, instruction: 'Варить 10 минут, вернуть курицу.' },
      ],
    },
    dinner: {
      id: 'mock_d1',
      name: 'Гречка с котлетой',
      description: 'Рассыпчатая гречка с сочной котлетой из говядины.',
      mealType: 'dinner',
      cookingTime: 30,
      difficulty: 'medium',
      ingredients: [
        { id: 'buckwheat', name: 'Гречка', amount: 100, unit: 'г', category: 'storable' },
        { id: 'beef', name: 'Говяжий фарш', amount: 150, unit: 'г', category: 'perishable' },
        { id: 'onion', name: 'Лук', amount: 50, unit: 'г', category: 'storable' },
        { id: 'oil', name: 'Масло', amount: 1, unit: 'ст.л.', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Отварить гречку.' },
        { stepNumber: 2, instruction: 'Смешать фарш с луком, сформировать котлеты.' },
        { stepNumber: 3, instruction: 'Обжарить котлеты по 5 минут с каждой стороны.' },
      ],
    },
  },
  {
    dayNumber: 2,
    breakfast: {
      id: 'mock_b2',
      name: 'Омлет с помидорами',
      description: 'Воздушный омлет со свежими помидорами.',
      mealType: 'breakfast',
      cookingTime: 10,
      difficulty: 'easy',
      ingredients: [
        { id: 'eggs', name: 'Яйца', amount: 3, unit: 'шт', category: 'storable' },
        { id: 'tomatoes', name: 'Помидоры', amount: 100, unit: 'г', category: 'perishable' },
        { id: 'oil', name: 'Масло', amount: 1, unit: 'ч.л.', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Взбить яйца.' },
        { stepNumber: 2, instruction: 'Вылить на сковороду, добавить нарезанные помидоры.' },
        { stepNumber: 3, instruction: 'Накрыть крышкой на 3 минуты.' },
      ],
    },
    lunch: {
      id: 'mock_l2',
      name: 'Греческий салат с курицей',
      description: 'Свежий салат с овощами, фетой и куриной грудкой.',
      mealType: 'lunch',
      cookingTime: 20,
      difficulty: 'easy',
      ingredients: [
        { id: 'chicken', name: 'Куриная грудка', amount: 150, unit: 'г', category: 'perishable' },
        { id: 'cucumber', name: 'Огурец', amount: 100, unit: 'г', category: 'perishable' },
        { id: 'feta', name: 'Сыр фета', amount: 60, unit: 'г', category: 'perishable' },
        { id: 'olives', name: 'Маслины', amount: 50, unit: 'г', category: 'storable' },
        { id: 'oil', name: 'Оливковое масло', amount: 1, unit: 'ст.л.', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Запечь курицу, нарезать.' },
        { stepNumber: 2, instruction: 'Нарезать овощи, добавить фету и маслины.' },
        { stepNumber: 3, instruction: 'Заправить маслом.' },
      ],
    },
    dinner: {
      id: 'mock_d2',
      name: 'Лосось с рисом',
      description: 'Нежный лосось на пару с отварным рисом.',
      mealType: 'dinner',
      cookingTime: 25,
      difficulty: 'easy',
      ingredients: [
        { id: 'salmon', name: 'Лосось', amount: 200, unit: 'г', category: 'perishable' },
        { id: 'rice', name: 'Рис', amount: 80, unit: 'г', category: 'storable' },
        { id: 'lemon', name: 'Лимон', amount: 0.5, unit: 'шт', category: 'perishable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Отварить рис.' },
        { stepNumber: 2, instruction: 'Приготовить лосось на пару 15 минут.' },
        { stepNumber: 3, instruction: 'Подать с лимоном.' },
      ],
    },
  },
  {
    dayNumber: 3,
    breakfast: {
      id: 'mock_b3',
      name: 'Творожная запеканка',
      description: 'Нежная запеканка из творога с изюмом.',
      mealType: 'breakfast',
      cookingTime: 40,
      difficulty: 'medium',
      ingredients: [
        { id: 'cottage', name: 'Творог', amount: 250, unit: 'г', category: 'perishable' },
        { id: 'eggs', name: 'Яйца', amount: 2, unit: 'шт', category: 'storable' },
        { id: 'raisins', name: 'Изюм', amount: 40, unit: 'г', category: 'storable' },
        { id: 'sugar', name: 'Сахар', amount: 2, unit: 'ст.л.', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Смешать творог, яйца, сахар и изюм.' },
        { stepNumber: 2, instruction: 'Выложить в форму.' },
        { stepNumber: 3, instruction: 'Выпекать при 180°C 30 минут.' },
      ],
    },
    lunch: {
      id: 'mock_l3',
      name: 'Борщ',
      description: 'Классический борщ со свёклой и говядиной.',
      mealType: 'lunch',
      cookingTime: 60,
      difficulty: 'medium',
      ingredients: [
        { id: 'beef', name: 'Говядина', amount: 200, unit: 'г', category: 'perishable' },
        { id: 'beet', name: 'Свёкла', amount: 150, unit: 'г', category: 'storable' },
        { id: 'cabbage', name: 'Капуста', amount: 150, unit: 'г', category: 'storable' },
        { id: 'potato', name: 'Картофель', amount: 150, unit: 'г', category: 'storable' },
        { id: 'sour_cream', name: 'Сметана', amount: 2, unit: 'ст.л.', category: 'perishable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Сварить говядину.' },
        { stepNumber: 2, instruction: 'Добавить овощи и варить 20 минут.' },
        { stepNumber: 3, instruction: 'Подать со сметаной.' },
      ],
    },
    dinner: {
      id: 'mock_d3',
      name: 'Паста болоньезе',
      description: 'Классическая паста с томатным соусом и фаршем.',
      mealType: 'dinner',
      cookingTime: 35,
      difficulty: 'medium',
      ingredients: [
        { id: 'pasta', name: 'Спагетти', amount: 100, unit: 'г', category: 'storable' },
        { id: 'beef', name: 'Говяжий фарш', amount: 150, unit: 'г', category: 'perishable' },
        { id: 'tomatoes', name: 'Томаты в соку', amount: 200, unit: 'г', category: 'storable' },
        { id: 'onion', name: 'Лук', amount: 60, unit: 'г', category: 'storable' },
      ],
      steps: [
        { stepNumber: 1, instruction: 'Обжарить лук и фарш.' },
        { stepNumber: 2, instruction: 'Добавить томаты, тушить 15 минут.' },
        { stepNumber: 3, instruction: 'Отварить пасту, подать с соусом.' },
      ],
    },
  },
]
